### ISSUE TITLE
Groundstate LU removes remarks

### ISSUE THREAD

**Issue by NikolasHB** [VATGER-Nav/edww-package#384]
Since a recent AIRAC update (I think) setting the departure state to LU removes all remarks in the tag. This is especially inconvenient for VFR traffic.

**Comment by hannesaltmann** [comment]
We changed nothing regarding the Groundradar Plugin (which manages the groundstates). 

The Groundstate is a temporary entry in one of the scratchpads, though this should normally not overwrite anything in the user's scratchpad. 

 I tested it myself and I couldn't reproduce the problem. Re-reinstalling the package might help. Also, we are not able to solve any plugin-related bugs. You can try to explain your issue here (if it still regularly exists after the re-install): https://forum.vatsim-scandinavia.org/t/plugins
